<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Convert2PDFServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Convert2PDFServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Convert2PDFServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws.pdf/">
    <import location="Convert2PDFService.wsdl" namespace="http://ws.pdf/"/>
    <plnk:partnerLinkType name="Convert2PDFLinkType">
        <plnk:role name="Convert2PDFRole" portType="ns:Convert2PDF"/>
    </plnk:partnerLinkType>
</definitions>
